#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/notifications
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDBDialect
#server:
#  port: 9003
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notifications?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    open-in-view: false

  data:
    redis:
      port: 6379
      host: localhost

  servlet:
    multipart:
      file-size-threshold: 2MB
      location: /tmp/s3
      max-file-size: 2MB
      max-request-size: 12MB

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

jwt:
  key: c3ByaW5nLWJvb3QtYXBpLWp3dC1zZWNyZXQta2V5LXN1cGVyLXNlY3JldC15ZXMteWVzLXllcy0yNAo=

scheduler:
  api:
    funding-product:
      views: "0 0 0 * * *"
  batch:
    funding: "0 0 1 * * *"

sse:
  timeout: 60000

logging:
  level:
    org:
      springframework:
#        security: debug
#        transaction:
#          interceptor: debug
#    com.zaxxer.hikari: trace
#    com.zaxxer.hikari.HikariConfig: debug

server:
  port: 9003
